### ISSUE TITLE
FART on very first request?

### ISSUE THREAD

**Issue by kwiat1990** [rossmoody/stitches-remix#1]
Hi, I would like to ask if this solution you don’t have this problem that when a user comes to your site for the very first time, then he didn’t see FART. The sam should be the case using incognito mode on every new request. 

I have very similar solution to yours and I can’t get rid of that problem. On Remix discussion page I was told it can’t really work on that initial request. 

If I switch to Tailwind and CSS approach, then I get another error. This time regarding class missmatch between server and client. 

Such a simple feature like color scheme is so far the most advanced one I’ve worked on for my hobby project.

**Comment by rossmoody** [comment]
I'm not sure if that's solvable with server request cookies via incognito windows since they aren't kept. That might be by design in this case.
