### ISSUE TITLE
Unable to get correct initial theme?

### ISSUE THREAD

**Issue by syeef** [rossmoody/stitches-remix#2]
Hey Ross,

Were you able to get automatic detection of the users theme from the OS to work with this approach? I'm trying to apply your technique whilst deploying to Cloudflare Pages, so I'm not sure if that makes any difference or if there's something I should take into account because of this.

I've been able to get the theme swapping to work using the button.

**Comment by rossmoody** [comment]
It's been a little while since I tinkered with this so it isn't fresh, but I believe if the user hasn’t set a theme manually and has a user prefers-color-mode preference, the logic grabs it from the request header and sets the theme accordingly.
